### ISSUE TITLE
Where is the implementation of MQTT-SN?

### ISSUE THREAD

**Issue by yangpu** [njh/dennet#1]
I have exactly the same design to communicate with MQTT-SN over RS485. 

What's your next plan for this project?

**Comment by njh** [comment]
Sorry, no code yet.

I did start playing with an Arduino implementation but had problems with the RS-485 driver not turning on and off cleanly enough and not having the right equipment to diagnose it. I suspect that the collision detection / backoff code is going to be hard work to get to work well.

Still interested but this project is currently on hold while I concentrate on other projects.

**Comment by njh** [comment]
Oh and I was going to start with Full-Duplex MQTT-SN; which would be much easier and only require data framing.

I managed to get four serial ports and a USB hub pretty cheaply:
https://twitter.com/njh/status/570298977310150656

**Comment by njh** [comment]
See also my MQTT-SN Serial Port bridge:
https://github.com/njh/mqtt-sn-tools

**Comment by yangpu** [comment]
I prefer to RS-485 for long distance communication. We need abstract communication design from MQTT-SN protocol, which means to simulate Full-Duplex communication by polling work mode of RS-485.

**Comment by njh** [comment]
I am not sure what "polling work mode" means?

RS-485 is just an electrical specification.

**Comment by greypanda** [comment]
I have used RS485 with ATMegas for many years. (Long before Arduino.) I had a very reliable working network that was programmed in Bascom (BASIC). Polling is the only practical way of simulating a "full duplex" network over 2 wires. But with the proper protocol ( realize that RS485 is NOT a protocol ), it can become a very robust, low cost solution that fits very well in the ATMega footprint. I think with a smart gateway, MQTT could be proxied over RS485.

**Comment by njh** [comment]
Thanks @greypanda   When I said "Full-Duplex" above, I was referring to having separate send/receive lines (four wires), to make things a bit easier.

But this project ("Dennet") is indeed about communicating over two wires. And ideally being able to operate without a master, so for example a Light Switch can publish/broadcast a message to a Lamp, even if the gateway has died. Higher levels of intelligence/automation would require a gateway/MQTT server/logic engine.

**Comment by greypanda** [comment]
That opens up a different "can-o-worms". I haven't found a way to manage the node-to-node communication without a central manager of some kind. It works OK with a simple static network, but once you start building a dynamic, rule-based system, SOMETHING has to keep track of the routing. And although most folks don't like to have multiple masters on an RS485 bus, I have built several systems with more than one master that work fine. Keep digging. It's a fascinating world out there!

**Comment by njh** [comment]
Thanks! I hope to have some time to do some more work on it in a couple of months :)

**Comment by greypanda** [comment]
The real problem with 2-wire without a master is contention (collisions). It's there for all kinds of shared-bus systems. (Remember 10-base ethernet?) If you really want a "masterless" network you might consider CAN bus, but then you get into more $$ and more complexity. And there is always the old reliable token-passing protocol. You never thought there was this much under that rock, did you?

**Comment by ghost** [comment]
Do you find anything good for this?

I would like to try to implement .NET Microframework based nodes with MQTT-SN

**Comment by njh** [comment]
I am no-longer planning to use MQTT-SN for this project.

**Comment by njh** [comment]
The thinking behind this change is that I want constrained devices to be able to talk to each other. Adding MQTT-SN doesn't add anything to the transactions between devices but does add complexity. I plan to still use MQTT, but have a protocol translator at the edge of the RS-485 network.
